require 'rubygems'
require 'rake'
require 'echoe'

Echoe.new('monetra', '0.0.2.6') do |p|
  p.description    = "A gem that uses the Monetra API to perform actions"
  p.url            = "http://github.com/winelibrary/monetra"
  p.author         = ["Dan Ahern", "John Kassimatis", "Brian Woolley"]
  p.email          = ["gems@danahern.com", "yonnage@gmail.com", "bushfreakz@gmail.com"]
  p.ignore_pattern = ["tmp/*", "script/*"]
  p.development_dependencies = []
end