require 'rubygems'
require 'rake'
require 'echoe'

Echoe.new('monetra', '0.0.2.2') do |p|
  p.description    = "A gem that uses the Monetra API to perform actions"
  p.url            = "http://github.com/winelibrary/monetra"
  p.author         = "Dan Ahern"
  p.email          = "gems@danahern.com"
  p.ignore_pattern = ["tmp/*", "script/*"]
  p.development_dependencies = []
end